### ISSUE TITLE
Issues with scoped packages

### ISSUE THREAD

**Issue by RandomByte** [alopezsanchez/web-tooling-benchmark-generator#4]
Cool project. I tried it with the `@ui5/cli` npm module but ran into an issue when creating the first file: `src/@ui5/cli-benchmark.js`. I think the slash in the library name needs to be stripped from the filename.

Also, the slash as well as the "@" needs to be removed from the generated JavaScript variable names as they will lead to syntax errors.

I worked around this locally, but I guess other projects might face the same issue.

**Comment by alopezsanchez** [comment]
Hello @RandomByte. It should have been fixed in `v1.0.1`.

Thank you for your feedback!
